version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridal-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
