# Generated by Django 4.2.30 on 2026-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bridaldress",
            name="dress_number",
            field=models.CharField(
                blank=True,
                help_text="Dress number/identifier",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="bridalroom",
            name="room_number",
            field=models.CharField(
                blank=True,
                help_text="Room number/identifier",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
